import { describe, expect, it } from "vitest";
import {
  buildPullRequestBody,
  buildRenderedPublishMessage,
} from "../src/target/publish-shared.js";

const messageVariables = {
  version: "1.2.3",
  output_path: "Casks/app.rb",
  tag_name: "v1.2.3",
  release_id: "123",
  release_name: "Release",
  release_url: "https://example.test/release/123",
};

describe("publish-shared message builders", () => {
  it("builds commit title/body and appends commit attribution", () => {
    const result = buildRenderedPublishMessage(
      {
        publishTitleTemplate: "release {{tag_name}}",
        publishBodyTemplate: "Source: {{release_url}}",
        publishAttribution: "both",
      },
      messageVariables,
    );

    expect(result).toEqual({
      title: "release v1.2.3",
      body: "Source: https://example.test/release/123\n\nGenerated by brew-up: https://github.com/dayflower/brew-up",
    });
  });

  it("replaces unknown variables with UNKNOWN in shared title rendering", () => {
    const result = buildRenderedPublishMessage(
      {
        publishTitleTemplate: "release {{tag_name}} {{missing_value}}",
        publishBodyTemplate: "",
        publishAttribution: "off",
      },
      messageVariables,
    );

    expect(result).toEqual({
      title: "release v1.2.3 UNKNOWN",
      body: "",
    });
  });

  it("builds PR body with pr attribution and returns undefined when empty", () => {
    const bodyWithAttribution = buildPullRequestBody(
      {
        publishBodyTemplate: "Source: {{release_url}}",
        publishAttribution: "pr",
      },
      messageVariables,
    );
    const emptyBody = buildPullRequestBody(
      {
        publishBodyTemplate: "",
        publishAttribution: "off",
      },
      messageVariables,
    );

    expect(bodyWithAttribution).toBe(
      "Source: https://example.test/release/123\n\nGenerated by [brew-up](https://github.com/dayflower/brew-up)",
    );
    expect(emptyBody).toBeUndefined();
  });
});
